-- Clarence Lawyer Portal full SQL Server schema
CREATE TABLE Roles (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL UNIQUE,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Users (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Email NVARCHAR(255) NOT NULL UNIQUE,
    FullName NVARCHAR(255) NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE UserRoles (
    UserId UNIQUEIDENTIFIER NOT NULL,
    RoleId UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY (UserId, RoleId),
    FOREIGN KEY (UserId) REFERENCES Users(Id),
    FOREIGN KEY (RoleId) REFERENCES Roles(Id)
);

CREATE TABLE Clients (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    RentManagerAccountId NVARCHAR(100) NULL,
    RmSyncStatus NVARCHAR(50) NOT NULL DEFAULT 'Pending',
    LastSyncedAtUtc DATETIME2 NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Properties (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    ClientId UNIQUEIDENTIFIER NOT NULL,
    AddressLine1 NVARCHAR(255) NOT NULL,
    AddressLine2 NVARCHAR(255) NULL,
    City NVARCHAR(100) NOT NULL,
    [State] NVARCHAR(50) NOT NULL,
    PostalCode NVARCHAR(20) NOT NULL,
    County NVARCHAR(100) NULL,
    RmPropertyId NVARCHAR(100) NULL,
    FOREIGN KEY (ClientId) REFERENCES Clients(Id)
);

CREATE TABLE Tenants (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    FullName NVARCHAR(255) NOT NULL,
    Unit NVARCHAR(50) NULL,
    Phone NVARCHAR(50) NULL,
    Email NVARCHAR(255) NULL,
    RmTenantId NVARCHAR(100) NULL
);

CREATE TABLE LegalCases (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    CaseNumber NVARCHAR(100) NOT NULL UNIQUE,
    ClientId UNIQUEIDENTIFIER NOT NULL,
    PropertyId UNIQUEIDENTIFIER NOT NULL,
    TenantId UNIQUEIDENTIFIER NOT NULL,
    Stage NVARCHAR(50) NOT NULL,
    MonthlyRent DECIMAL(18,2) NOT NULL,
    BalanceOwed DECIMAL(18,2) NOT NULL,
    LateFees DECIMAL(18,2) NOT NULL DEFAULT 0,
    CourtCosts DECIMAL(18,2) NOT NULL DEFAULT 0,
    LastPaymentDate DATE NULL,
    NextDeadline DATE NULL,
    CourtDate DATE NULL,
    SettlementStatus NVARCHAR(50) NULL,
    OutcomeStatus NVARCHAR(50) NULL,
    IsClosed BIT NOT NULL DEFAULT 0,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    FOREIGN KEY (ClientId) REFERENCES Clients(Id),
    FOREIGN KEY (PropertyId) REFERENCES Properties(Id),
    FOREIGN KEY (TenantId) REFERENCES Tenants(Id)
);

CREATE TABLE RentManagerSubmissions (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    RmSubmissionId NVARCHAR(100) NOT NULL,
    ClientId UNIQUEIDENTIFIER NOT NULL,
    PropertyId UNIQUEIDENTIFIER NOT NULL,
    TenantId UNIQUEIDENTIFIER NOT NULL,
    MonthlyRent DECIMAL(18,2) NOT NULL,
    BalanceOwed DECIMAL(18,2) NOT NULL,
    VerificationStatus NVARCHAR(50) NOT NULL,
    ReceivedAtUtc DATETIME2 NOT NULL,
    Accepted BIT NOT NULL DEFAULT 0,
    AcceptedAtUtc DATETIME2 NULL,
    AcceptedByUserId UNIQUEIDENTIFIER NULL,
    FOREIGN KEY (ClientId) REFERENCES Clients(Id),
    FOREIGN KEY (PropertyId) REFERENCES Properties(Id),
    FOREIGN KEY (TenantId) REFERENCES Tenants(Id),
    FOREIGN KEY (AcceptedByUserId) REFERENCES Users(Id)
);

CREATE TABLE CaseTimelineEvents (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    LegalCaseId UNIQUEIDENTIFIER NOT NULL,
    Stage NVARCHAR(50) NOT NULL,
    Notes NVARCHAR(1000) NULL,
    ActorUserId UNIQUEIDENTIFIER NULL,
    AtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    FOREIGN KEY (LegalCaseId) REFERENCES LegalCases(Id),
    FOREIGN KEY (ActorUserId) REFERENCES Users(Id)
);

CREATE TABLE FormTemplates (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Jurisdiction NVARCHAR(100) NOT NULL,
    TemplateHtml NVARCHAR(MAX) NOT NULL,
    RequiredFieldsJson NVARCHAR(MAX) NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE GeneratedDocuments (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    LegalCaseId UNIQUEIDENTIFIER NOT NULL,
    FormTemplateId UNIQUEIDENTIFIER NOT NULL,
    FileName NVARCHAR(255) NOT NULL,
    FilePath NVARCHAR(500) NOT NULL,
    GeneratedByUserId UNIQUEIDENTIFIER NULL,
    GeneratedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    FOREIGN KEY (LegalCaseId) REFERENCES LegalCases(Id),
    FOREIGN KEY (FormTemplateId) REFERENCES FormTemplates(Id),
    FOREIGN KEY (GeneratedByUserId) REFERENCES Users(Id)
);

CREATE TABLE CaseNotes (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    LegalCaseId UNIQUEIDENTIFIER NOT NULL,
    NoteText NVARCHAR(MAX) NOT NULL,
    CreatedByUserId UNIQUEIDENTIFIER NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    FOREIGN KEY (LegalCaseId) REFERENCES LegalCases(Id),
    FOREIGN KEY (CreatedByUserId) REFERENCES Users(Id)
);

CREATE TABLE AuditLogs (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    LegalCaseId UNIQUEIDENTIFIER NULL,
    ActorUserId UNIQUEIDENTIFIER NULL,
    ActionType NVARCHAR(100) NOT NULL,
    OldValueJson NVARCHAR(MAX) NULL,
    NewValueJson NVARCHAR(MAX) NULL,
    SourceSystem NVARCHAR(100) NOT NULL,
    IpAddress NVARCHAR(64) NULL,
    DeviceInfo NVARCHAR(255) NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    FOREIGN KEY (LegalCaseId) REFERENCES LegalCases(Id),
    FOREIGN KEY (ActorUserId) REFERENCES Users(Id)
);

CREATE TABLE RentManagerSyncLogs (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    LegalCaseId UNIQUEIDENTIFIER NULL,
    SyncDirection NVARCHAR(20) NOT NULL,
    SyncType NVARCHAR(100) NOT NULL,
    Status NVARCHAR(50) NOT NULL,
    RequestPayload NVARCHAR(MAX) NULL,
    ResponsePayload NVARCHAR(MAX) NULL,
    ErrorMessage NVARCHAR(MAX) NULL,
    RetryCount INT NOT NULL DEFAULT 0,
    SyncedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    FOREIGN KEY (LegalCaseId) REFERENCES LegalCases(Id)
);
GO
